In [73]:
import numpy as np 

def build_poly(tx, degree):
    for idx, x in enumerate(tx.T):
        if idx == 0:
            arr_out = build_poly_one_column(x, degree)
        else:
            arr_out = np.c_[arr_out, build_poly_one_column(x, degree)]
    return arr_out

def build_poly_oxne_column(x, degree):
    arr = np.zeros((x.shape[0], degree+1))
    print(arr.shape)
    for degre in range(degree+1):
        arr[:,degre] = np.power(x, degre)
    return arr

In [74]:
tx = np.array([[1,1,1],[2,3,2],[3,3,3],[4,4,4]])
print(tx.shape)
print(tx.shape[0])
print(build_poly_4(tx, 3))
tx = np.array([1,2,3,4])
print(build_poly_2(tx, 3))

(4, 3)
4
(4, 4)
(4, 4)
(4, 4)
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  2.  4.  8.  1.  3.  9. 27.  1.  2.  4.  8.]
 [ 1.  3.  9. 27.  1.  3.  9. 27.  1.  3.  9. 27.]
 [ 1.  4. 16. 64.  1.  4. 16. 64.  1.  4. 16. 64.]]
(4, 4)
[[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]
